defaultPortal: wilby-jones
portals:
  - name: wilby-jones
    portalId: 145762151
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJKltd-XMxISQlNQMl8kQEwrAgUACAkCeSgCGOfOwEUg94nmHyju6QwyFH_hEc_SPRYs2YfDFYcQOc0OlEu4OhZCU1AyXyRATCsCCQAIEwYGnPABbgFCQhT9TYRqcivyifQkhwvi9NSiEWhQyUoDZXUxUgBaAGABaABwAHgA
        expiresAt: '2025-09-24T13:32:54.844Z'
    accountType: APP_DEVELOPER
    personalAccessKey: >-
      CiRldTEtMzY2MC1mNmUyLTQzNTktOWJkYy1lZThiNDk0YjRhOGYQ587ARRj3ieYfKhkABeaRgjDGvY9gBNjDLEct165HONls0tqlSgNldTE
